# Hackathon topics configuration
# Easy to update for different hackathons

HACKATHON_TOPICS = [
    "Agentic AI",
    "LLMs",
    "RAG",
    "Voice AI",
    "Data Infra",
    "Observability",
    "Robotics",
    "Hardware",
    "Web3",
    "DeFi",
    "Analytics",
    "Creative AI",
    "Healthcare",
    "Education",
    "Social Impact",
    "Multimodal AI",
    "Edge AI",
    "Autonomous Agents",
    "Cloud Infra",
    "Cybersecurity",
    "Ethical AI",
    "Open Source",
    "Fintech",
    "Ad Tech",
    "Blockchain",
    "IoT",
    "Dev Tools",
    "Biotech",
    "AR/VR",
    "Sustainability",
]
